### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by ZAYEC77** [RuolinZheng08/renpy-chess-engine#1]
did you think about python 3 compatibility?

**Comment by RuolinZheng08** [comment]
Hi, yep, it's under consideration. I have other projects going on so this hasn't been on my priority list. I may give it more priority if there's popular demand/commission request.

Also v2 is preferred to v1: https://github.com/RuolinZheng08/renpy-chess
I would prioritize adding python3 support for v2 over for v1 (this repo).

**Comment by ZAYEC77** [comment]
I see
thank you for your response
